<style>

.policy {
    margin-top: 40px;
    margin-left: 13%;
    margin-right: 13%;
}

</style>



<?php
include("header.php");
include("analytics.php");
?>

<div class="policy">
    <div class="page-header">
        <h1>Nosco Management Solutions Limited</h1>
        <h6><a href="https://noscosystems.com/">Nosco</a> &middot; <a href="https://www.nospos.com/">NosPos</a> &middot; <a href="http://www.captivad.co.uk/">CaptivAd</a></h6>
        <br>
        <h2>Privacy Policy</h2>
        <br>
        <p>Our websites include contact forms that you may wish to use to approach us regarding the services offered on that website.</p>
        <p>When you submit a contact form, the data that you provide will be directed to the official admin email address of Nosco Systems.</p>
        <p>We will use this data to contact you to discuss the services described on the website and will retain this data in our records during any discussion, negotiation, and subsequent business relationship between yourself and us.</p>
        <p>We will not use your data for purposes unrelated to the services outlined in the website, for general marketing, nor pass your data to any third party, unless you have expressly permitted us to do so.</p>
        <p>We will make reasonable attempts to contact you using the data provided, however, if we are unable to establish any contact within two months of receiving your submission on this contact form, your data will be removed from our records.</p>
        <br><br>
        <h2>Cookie Policy</h2>
        <br>
        <p>Our websites use cookies as part of the Google Analytics service, for the purpose of tracking visitor traffic and trends. No data generated by Google Analytics is capable of personally identifying any individual user.</p>
    </div>
</div>


